# ─────────────────────────────────────────────────────────────────────────────
# TEMPLATE — DO NOT EDIT THIS FILE.
#
# This folder is the host-side companion to the `_template-bare-metal`
# profile in `flake.nix`. It is intentionally a skeleton: copy it, don't
# modify it in place.
#
# How to use this template
# ────────────────────────
#  1. Copy the directory:
#         cp -r nixos/hosts/_template-bare-metal nixos/hosts/<your-host>
#  2. Copy the matching profile entry in `flake.nix` (the block tagged
#     `TEMPLATE — DO NOT EDIT, DO NOT DEPLOY`) to a new key with the same
#     name as your folder, set `hostname` to `<your-host>`, and tweak the
#     extras (graphics, gaming, etc.) to taste.
#  3. Edit your copy of this `default.nix` (NOT this template) — flip
#     between UEFI / BIOS disko layouts, override the disk device, and
#     drop in any host-specific bootloader or hardware quirks below or
#     in `./nixos/`.
#  4. Run `nixos-anywhere` from WSL with
#     `--generate-hardware-config nixos-generate-config nixos/hosts/<your-host>/nixos/hardware-configuration.nix`
#     — the `pathExists` guard below lets the flake evaluate before that
#     file exists, then auto-imports it after first install.
#
# Layout of a host folder (this template demonstrates all four)
# ─────────────────────────────────────────────────────────────
#     nixos/hosts/<your-host>/
#       default.nix               # ← this file: NixOS-side host entry
#       home.nix                  # HM-side host entry (auto-discovered)
#       nixos/                    # NixOS sub-modules for this host only
#         hardware-configuration.nix
#       home/                     # HM sub-modules for this host only
#
# What's wired in by default
# ──────────────────────────
#  - Disko UEFI layout (`single-disk-uefi.nix`): GPT, 512 MiB ESP at
#    `/boot`, ext4 root at `/`, paired with systemd-boot. Compatible with
#    the impermanence wipe-root pattern (preserves top-level `boot` and
#    `nix`, so the bootloader and `/nix/persist` survive every reboot).
#  - Auto-import of `./nixos/hardware-configuration.nix` once it lands.
#
# Customization points
# ────────────────────
#  - Switch to BIOS/MBR (legacy firmware, VirtualBox without "Enable EFI",
#    older bare metal): swap the disko import for `single-disk-bios.nix`.
#  - Different disk device (NVMe, second SATA, etc.): override
#    `disko.devices.disk.main.device` below.
#  - Per-host kernel modules, microcode, fan curves, dual-boot grub,
#    LUKS, swap, separate `/home`, etc.: drop a file under `./nixos/`
#    and add it to `imports` here (NOT in this template).
# ─────────────────────────────────────────────────────────────────────────────
{lib, ...}: {
  imports =
    [
      # Disk layout. Pick one — the two layouts in `nixos/disko/` are both
      # impermanence-safe (they leave `boot` and `nix` outside the wipe).
      #
      #   single-disk-uefi.nix — GPT + ESP + ext4 + systemd-boot (default)
      #   single-disk-bios.nix — GPT + BIOS-boot stub + ext4 + GRUB
      #
      ../../disko/single-disk-uefi.nix
      # ../../disko/single-disk-bios.nix
    ]
    ++ (
      # Chicken-and-egg guard for first-time installs.
      #
      # On a brand-new machine this file does not exist yet — `nixos-anywhere
      # --generate-hardware-config nixos-generate-config <path>` produces it
      # by SSHing into the booted minimal ISO, running `nixos-generate-config
      # --no-filesystems --root /mnt --show-hardware-config` on the target,
      # and writing the output back here. The flake must still evaluate
      # before that file lands, so we guard the import.
      #
      # After the first successful install, commit the generated file:
      #     git add nixos/hosts/<your-host>/nixos/hardware-configuration.nix
      #     git commit -m "Add hardware-configuration for <your-host>"
      let
        hw = ./nixos/hardware-configuration.nix;
      in
        if builtins.pathExists hw
        then [hw]
        else []
    );

  # Override the disk device if the target is not /dev/sda.
  # Common values:
  #   - NVMe:           "/dev/nvme0n1"
  #   - Second SATA:    "/dev/sdb"
  #   - VirtIO (cloud): "/dev/vda"
  #
  # disko.devices.disk.main.device = lib.mkForce "/dev/nvme0n1";

  # Host-specific bootloader / kernel / hardware tweaks go below in your
  # COPY of this file. Examples:
  #
  #   boot.kernelParams = ["quiet" "splash"];
  #   boot.kernelModules = ["kvm-intel"];
  #   hardware.cpu.intel.updateMicrocode = true;
  #   services.fwupd.enable = true;
  #
  # Or, for anything more than a few lines, drop a sub-module under
  # `./nixos/` and import it from the `imports` list above.
  #
  # Keep this template empty — it should always evaluate cleanly so
  # `nix flake check` stays green.
}
