# ─────────────────────────────────────────────────────────────────────────────
# TEMPLATE — DO NOT EDIT THIS FILE.
#
# Per-profile Home Manager entry. Auto-discovered by `mkProfile` whenever
# `nixos/hosts/<profile-name>/home.nix` exists. Use this for HM-side
# config that only applies to one host (per-host shell aliases, per-host
# desktop tweaks, etc.).
#
# Sub-modules under `./home/` are the recommended place for anything
# non-trivial — keep this file as a thin import list so the structure
# stays uniform across hosts. See `nixos/hosts/nixos-wsl/home.nix` for a
# real example.
#
# How to use
# ──────────
#   1. Copy this folder along with the matching profile entry, as
#      described in `default.nix`.
#   2. Drop your HM sub-modules into `./home/` next to this file.
#   3. Reference them from the `imports` list below.
#
# If you don't need any HM-side per-host config, delete this file in
# your copy — the auto-discovery silently skips it when absent.
# ─────────────────────────────────────────────────────────────────────────────
{...}: {
  imports = [
    # ./home/example.nix
  ];
}
