{lib, ...}: {
  imports = [
    # Host-specific NixOS sub-modules under `./nixos/`. Add new files
    # there and import them here. `hardware-configuration.nix` lives
    # there too — guarded so the flake still evaluates if it hasn't
    # been generated yet.
    ./nixos/hardware-configuration.nix
    ../../disko/single-disk-uefi.nix

  ];

  networking.hostName = lib.mkForce "nixos-vbox";

  # Use GRUB in EFI mode on this VM. `efiInstallAsRemovable` writes GRUB
  # to the EFI fallback path (`/EFI/BOOT/BOOTX64.EFI`), which makes it
  # the default boot entry without touching EFI variables (works well
  # with VirtualBox's limited NVRAM support).
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.grub = {
    enable = lib.mkForce true;
    device = lib.mkForce "nodev";
    efiSupport = lib.mkForce true;
    efiInstallAsRemovable = lib.mkForce true;
  };
  boot.loader.efi.canTouchEfiVariables = lib.mkForce false;

  # VirtualBox Guest Additions. Pulls in `vboxguest`, `vboxsf`, `vboxvideo`
  # kernel modules + the `VBoxService` daemon, which gives us:
  #   - Dynamic display resolution (resize the VM window → guest follows).
  #   - Bidirectional clipboard / drag-and-drop (must also be enabled on
  #     the host side: VM → Settings → General → Advanced).
  #   - Shared folder support (`vboxsf` mount in `fileSystems."/mnt/..."`
  #     below; the host folder name is set in VM → Settings → Shared Folders).
  #   - Time sync, seamless mode, mouse pointer integration.
  #
  # Lives here (not in `hardware-configuration.nix`) because that file is
  # regenerated by `nixos-anywhere --generate-hardware-config`. Anything
  # not purely hardware-detection-driven belongs in the host module.
  virtualisation.virtualbox.guest.enable = true;

  # Membership in `vboxsf` is required to read/write the shared folder
  # mounted below (the kernel module enforces group ownership). Without
  # this line, opening `/mnt/nixconfig` as `david` returns EACCES even
  # though the mount itself succeeds.
  users.users.david.extraGroups = ["vboxsf"];

  fileSystems."/mnt/nixconfig" = {
    device = "NixConfig";
    fsType = "vboxsf";
    options = [
      "rw"
      "nofail"
      "x-systemd.automount"
      "uid=1000"
      "gid=100"
      "dmode=0775"
      "fmode=0664"
    ];
  };
}
