{
  config,
  pkgs,
  lib,
  ...
}: let
  identity = import ../_user-identity.nix;
in {
  imports = [
    ./dev/claude-code.nix
    ./dev/cursor.nix
    ./dev/dbhub.nix
  ];

  home.packages = with pkgs;
    [
      devenv
      direnv
      vscode
      code-cursor
      uv
      pixi
      tig # git show | tig
      diffnav # git diff pager with file tree (wraps delta)
      delta # required backend for diffnav
      quarto
      tableplus
      lazydocker # docker TUI
      nodejs
      bun
      nixd # Nix language server
      tmux # required at runtime by dmux
      sesh # fuzzy tmux session picker (prefix+S; fzf comes from dual/fish.nix)
      (callPackage ./dev/dmux {}) # agent multiplexer over tmux + git worktrees
    ];

  # sesh binds prefix+S to an fzf picker over tmux sessions, zoxide dirs and
  # git repos. It lives in its own file because ~/.tmux.conf is generated by
  # dmux onboarding and is not managed here — that file only gains a
  # `source-file` line pointing at this one.
  #
  # `sesh connect` issues switch-client when it is already inside tmux, so
  # picking a session from a dmux pane switches the client instead of nesting
  # a second server inside the pane.
  #
  # The listing covers live tmux sessions, configured ones, and zoxide's
  # frecent directories. sesh treats a missing zoxide as fatal rather than
  # skipping it, so this depends on programs.zoxide in modules/dual/fish.nix.
  #
  # ctrl-x inside the picker kills the highlighted session and reloads the
  # list; `{2..}` drops the icon column. Keep this in step with the ctrl-g
  # equivalent in modules/dual/fish.nix (browse_sessions) — same picker, two
  # entry points.
  #
  # `run-shell -b` is load-bearing — an unbackgrounded run-shell blocks the
  # tmux server's command queue for as long as the fzf popup is open, which is
  # the same wedge the dmux resize-hook patch exists to fix.
  xdg.configFile."tmux/sesh.conf".text = ''
    bind-key S run-shell -b "sesh connect \"$(sesh list --icons | fzf-tmux -p 80%,70% --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' --header 'enter: attach · ctrl-x: kill · esc: cancel' --bind 'ctrl-x:execute-silent(tmux kill-session -t {2..} 2>/dev/null)+reload(sesh list --icons)')\""
  '';

  programs.gh = {
    enable = true;
    extensions = [pkgs.gh-stack];
    settings = {
      git_protocol = "https";
      aliases.co = "pr checkout";
      aliases.pc = "pr create";
    };
  };

  # gh-dash is installed here (not in programs.gh.extensions above): this
  # module adds pkgs.gh-dash to home.packages AND registers it as a gh
  # extension, and writes ~/.config/gh-dash/config.yml from `settings`.
  programs.gh-dash = {
    enable = true;
    settings = {
      # Use diffnav to view PR/issue diffs (the `d` key) instead of less.
      pager.diff = "diffnav";
      # Fixes "local path to repo not specified": map owner/* -> local clone.
      # All repos are cloned flat under ~/github/<repo>; the value's trailing
      # /* is replaced with the repo name at checkout time.
      repoPaths = {
        "DSestu/*" = "~/github/*";
        "sencrop/*" = "~/github/*";
      };
      # Overriding a builtin REPLACES its default keys (gh-dash calls
      # SetKeys), so binding up/down/nextSection/prevSection to only the
      # arrow keys removes the default k/j/l/h vim bindings.
      keybindings = {
        universal = [
          {
            key = "up";
            builtin = "up";
          } # was up/k -> drop k
          {
            key = "down";
            builtin = "down";
          } # was down/j -> drop j
          {
            key = "right";
            builtin = "nextSection";
          } # was right/l -> drop l
          {
            key = "left";
            builtin = "prevSection";
          } # was left/h -> drop h
          {
            key = "ctrl+down";
            builtin = "pageDown";
          } # preview page down (was ctrl+d)
          {
            key = "ctrl+up";
            builtin = "pageUp";
          } # preview page up (was ctrl+u)
        ];
        # `label` defaults to L in both views; move it to lowercase l
        # (freed up now that l no longer navigates sections).
        prs = [
          {
            key = "l";
            builtin = "label";
          }
        ];
        issues = [
          {
            key = "l";
            builtin = "label";
          }
        ];
      };
    };
  };

  programs.git = {
    enable = true;
    settings = {
      user.name = identity.gitName;
      user.email = identity.gitEmail;
      init.defaultBranch = "main";
      pull.rebase = false;
      core.pager = "diffnav";
    };
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    settings."*" = {
      ForwardAgent = false;
      AddKeysToAgent = "no";
      Compression = false;
      ServerAliveInterval = 0;
      ServerAliveCountMax = 3;
      HashKnownHosts = false;
      UserKnownHostsFile = "~/.ssh/known_hosts";
      ControlMaster = "no";
      ControlPath = "~/.ssh/master-%r@%n:%p";
      ControlPersist = "no";
    };
    # Some networks block outbound port 22. GitHub serves SSH on 443 at
    # ssh.github.com with the same host keys, so alias them to github.com.
    settings."github.com" = {
      HostName = "ssh.github.com";
      Port = 443;
      HostKeyAlias = "github.com";
    };
  };
  services.ssh-agent.enable = true;
}
